[SheetConfig]
    sheet_name              = "PROJECTCONFIG"
    colomn_room             = "B"
    colomn_room_number      = "A"
    colomn_light            = "L"
    colomn_light_type       = "K"
    colomn_shade            = "O"
	colomn_shade_type		= "N"
    start_row               = 58

[CoreSignal]
    prefix	= "ROOM"
	name = "PL_"

[[PanelRoomName]]
    prefix	= "Room"
	name = "Name"

# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "light"
# 	device_type = "C"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = ""
# 	core_suffix = "ON"
# 	panel_suffix = "On"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "light"
# 	device_type = "C"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = ""
# 	core_suffix = "ON_FB"
# 	panel_suffix = "On_fb"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "light"
# 	device_type = "C"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = ""
# 	core_suffix = "OFF"
# 	panel_suffix = "Off_fb"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "light"
# 	device_type = "D"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = ""
# 	core_suffix = "RAISE"
# 	panel_suffix = "Raise"
[[Signals]]
	override_room_prefix = ""
	override_core_name = ""
	override_panel_name = ""
	override_device_name = ""
	room_level_signal = 0
	system_type = "light"
	device_type = "D"
	core_signal_modif = "LIGHT"
	panel_signal_modif = ""
	core_suffix = "DIM"
	panel_suffix = "Lower"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "light"
# 	device_type = "C"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = ""
# 	core_suffix = "LVL"
# 	panel_suffix = "Level"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "light"
# 	device_type = "D"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = "_dimmer"
# 	core_suffix = "LVL_FB"
# 	panel_suffix = "Current_Level"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "shade"
# 	device_type = "C"
# 	core_signal_modif = "SHADE"
# 	panel_signal_modif = ""
# 	core_suffix = "OPEN"
# 	panel_suffix = "Open"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "shade"
# 	device_type = "C"
# 	core_signal_modif = "SHADE"
# 	panel_signal_modif = ""
# 	core_suffix = "OPEN_FB"
# 	panel_suffix = "Open_fb"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "shade"
# 	device_type = "C"
# 	core_signal_modif = "SHADE"
# 	panel_signal_modif = ""
# 	core_suffix = "CLOSE"
# 	panel_suffix = "Close"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "shade"
# 	device_type = "C"
# 	core_signal_modif = "SHADE"
# 	panel_signal_modif = ""
# 	core_suffix = "STOP"
# 	panel_suffix = "Stop"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "shade"
# 	device_type = "C"
# 	core_signal_modif = "SHADE"
# 	panel_signal_modif = ""
# 	core_suffix = "STOP_FB"
# 	panel_suffix = "Stop_fb"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "shade"
# 	device_type = "C"
# 	core_signal_modif = "SHADE"
# 	panel_signal_modif = ""
# 	core_suffix = "LVL"
# 	panel_suffix = "Level"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = ""
# 	room_level_signal = 0
# 	system_type = "shade"
# 	device_type = "C"
# 	core_signal_modif = "SHADE"
# 	panel_signal_modif = ""
# 	core_suffix = "LVL_FB"
# 	panel_suffix = "Current_level"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = "Lighting_Scene_1"
# 	room_level_signal = -1
# 	system_type = "light"
# 	device_type = "C"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = ""
# 	core_suffix = "SCENE_01"
# 	panel_suffix = "Recall"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = "Lighting_Scene_2"
# 	room_level_signal = -1
# 	system_type = "light"
# 	device_type = "C"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = ""
# 	core_suffix = "SCENE_02"
# 	panel_suffix = "Recall"
# [[Signals]]
# 	override_room_prefix = ""
# 	override_core_name = ""
# 	override_panel_name = ""
# 	override_device_name = "Lighting_Scene_3"
# 	room_level_signal = -1
# 	system_type = "light"
# 	device_type = "C"
# 	core_signal_modif = "LIGHT"
# 	panel_signal_modif = ""
# 	core_suffix = "SCENE_03"
# 	panel_suffix = "Recall"
